"""Update Property model to new detailed schema

Revision ID: 16294eb5c625
Revises: 9051a92421c2
Create Date: 2025-05-30 05:34:55.655220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16294eb5c625'
down_revision = '9051a92421c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cat', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('total_floors', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('m', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('s', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('s_kh', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('blkn', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('p', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('d_kv', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('year', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('photos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(length=512), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('district',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('area',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('seller_phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.alter_column('external_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('added_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_properties_source_url'))
        batch_op.drop_constraint(batch_op.f('_source_external_id_uc'), type_='unique')
        batch_op.create_unique_constraint('_source_external_id_uc', ['source', 'external_id'])
        batch_op.create_index(batch_op.f('ix_properties_link'), ['link'], unique=False)
        batch_op.drop_column('source_url')
        batch_op.drop_column('image_urls')
        batch_op.drop_column('year_built')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_built', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('image_urls', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('source_url', sa.VARCHAR(length=512), nullable=True))
        batch_op.drop_index(batch_op.f('ix_properties_link'))
        batch_op.drop_constraint('_source_external_id_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_source_external_id_uc'), ['source_url', 'external_id'])
        batch_op.create_index(batch_op.f('ix_properties_source_url'), ['source_url'], unique=False)
        batch_op.alter_column('added_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('external_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('seller_phone',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('condition',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('area',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('district',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('link')
        batch_op.drop_column('photos')
        batch_op.drop_column('source')
        batch_op.drop_column('year')
        batch_op.drop_column('d_kv')
        batch_op.drop_column('street')
        batch_op.drop_column('p')
        batch_op.drop_column('blkn')
        batch_op.drop_column('s_kh')
        batch_op.drop_column('s')
        batch_op.drop_column('m')
        batch_op.drop_column('total_floors')
        batch_op.drop_column('status')
        batch_op.drop_column('cat')

    # ### end Alembic commands ###
