"""Modify PropertyImage to store LargeBinary image_data, remove image_path

Revision ID: c2e2ac311c69
Revises: 50f6fdcedc95
Create Date: 2025-05-30 05:42:22.032624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e2ac311c69'
down_revision = '50f6fdcedc95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=512), nullable=False))
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
